title: "Jonny Greenwood | Data Portfolio"
description: "Data Analytics • Forecasting • Power BI • SQL • Python"
url: "https://jonnylgreenwood.github.io"
baseurl: "/portfolio-site"
# logo: /assests/images/siteicon/android-chrome-512x512.png
# favicon: /assests/images/siteicon/android-chrome-512x512.png

# Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
show_navbar: true
plugins:
  - jekyll-include-cache

custom_css:
  - /assets/css/custom.css

# Optional: enable syntax highlighting and author info
markdown: kramdown
highlighter: rouge

# Layout
sidebar:
  position: left

# Navigation
navigation:
  - main

sass:
  style: compressed

author:
  name: "Jonny Greenwood"
  avatar: ""   # or leave blank if not ready
  bio: "Another data analyst and travelling photographer."
  location: "Leeds, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jonnylgreenwood"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jonathanlgreenwood/"
    - label: "Linktr.ee"
      icon: "fas fa-globe"
      url: "https://linktr.ee/greenwoodanalytics"
