title: "Jonny Greenwood | Data Portfolio"
description: "Data Analytics | Power BI | SQL | Alteryx | Python"
remote_theme: pages-themes/minimal@v0.2.0
baseurl: /portfolio-site


plugins:
  - jekyll-remote-theme

include:
  - _layouts
  - assets/css/style.css

# Optional – tweak how URLs are handled
markdown: kramdown
highlighter: rouge

# Navigation links (optional)
navigation:
  - title: Home
    url: /
  - title: Business Insights
    url: /business-insights
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Socials (if you want these later)
github:
  is_project_page: false
  owner_url: "https://github.com/jonnygreenwood"
  owner_name: "Jonny Greenwood"
